[package]
name = "sloth256-189"
version = "0.1.0"
description = "Encoder/decoder for the Subspace Network Blockchain based on the SLOTH permutation"
edition = "2018"
license = "MIT"
repository = "https://github.com/dot-asm/sloth256-189"
include = [
    "/src",
    "/Cargo.toml",
]

[features]
default = []
no-asm = []

[build-dependencies]
cc = { git = "https://github.com/dot-asm/cc-rs", branch = "cuda-dlink" }
glob = "0.3"
which = "^4.0"

[dev-dependencies]
criterion = "0.3.4"
rand = "0.8.3"
rayon = "1.5.1"

[[bench]]
name = "sloth256-189"
harness = false
